name: ConquestCore
main: com.conquestmc.core.CorePlugin
version: "0.1"
description: "Core plugin"
commands:
  gamemode:
    description: "Change a players gamemode"
    aliases:
      - gm
    usage: "/gm <survivalgames mode>"
  giverank:
    description: "Change a players rank"
    usage: "/giverank <player> <rank>"
  friends:
    description: "Default friend command"
    aliases:
      - f
      - friend
  punish:
    description: "Staff punish command"
    aliases:
      - p
  ph:
    description: "Punish history command"
  hub:
    description: "hub command"
  demote:
    description: "demotes a user from their staff rank"
  givecosmetic:
    description: "Give a cosmetic to a player"
  drachma:
    description: "Command to manage drachma"
  speed:
    description: "Changes flight and walking speed"
permissions:
  core.gamemode:
    description: "gamemode perm"
  core.gamemode.others:
    description: "Gamemode others perm"
  staff.punish:
    description: "Punish perm"
  staff.ph:
    description: "Punish history perm"
  group.admin:
    description: "Admin perm"