name: ConquestCore
main: com.conquestmc.core.CorePlugin
version: "0.1"
description: "Core plugin"
commands:
  gamemode:
    description: "Change a players gamemode"
    aliases:
      - gm
    usage: "/gm <game mode>"
  setrank:
    description: "Change a players rank"
    usage: "/setrank <player> <rank>"
permissions:
  core.gamemode:
    description: "gamemode perm"
  core.gamemode.others:
    description: "Gamemode others perm"